# Generated by Django 3.2.6 on 2023-06-20 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-id'], 'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
    ]
