# Generated by Django 3.2.6 on 2023-06-20 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['-name'], 'verbose_name': 'Teacher', 'verbose_name_plural': 'Teachers'},
        ),
    ]
